### ISSUE TITLE
Add test to ensure that all characters are valid UTF-8

### ISSUE THREAD

**Issue by ablack3** [OHDSI/PhenotypeLibrary#12]
I would like to propose ensuring that all json and sql files in the Phenotype library contain Unicode encoded characters. Preferably all characters would be valid UTF-8. Ensuring that all characters are valid UTF8 will make files easier to read into R. See https://rdrr.io/rforge/stringi/man/stringi-encoding.html for some background.

1. I propose converting any non-utf8 encoded characters to their utf8 counterparts (e.g.  "Sjögren's syndrome")
2. Adding a test that would check to make sure all text files contain only valid utf8 characters
3. Adding a dataframe/tibble to the package that would contain one row per cohort with metadata, json (as a list column), and sql (as a list column) so that loading the package in R would provide instant access to all phenotype and cohort data the package provides.

Currently there are a number of files that contain non-utf8 (ansi) characters.

```r
# verify that all text is valid utf-8
library(dplyr)
phenotypeIds <- list.files("inst") %>%
  stringr::str_subset("\\d+")

jsonFiles <- purrr::map(phenotypeIds, ~paste0(glue::glue("inst/{.}/") , list.files(glue::glue("inst/{.}")))) %>%
  unlist() %>%
  stringr::str_subset("\\.json")

df <- tibble::tibble(jsonFiles) %>%
  mutate(isutf8 = purrr::map(jsonFiles, ~stringi::stri_enc_isutf8(readr::read_lines_raw(.)))) %>%
  mutate(bad_lines = purrr::map_chr(isutf8, ~paste(which(!.), collapse = ","))) %>%
  filter(bad_lines != "") %>%
  mutate(notutf8 = paste("file:", jsonFiles, "lines:", bad_lines)) %>%
  select(notutf8)

if(nrow(df) != 0){
  message(paste0(c("The following lines contain non-utf8 characters", df$notutf8), collapse = "\n"))
}

#> The following lines contain non-utf8 characters
#> file: inst/254443000/254443001.json lines: 24,30
#> file: inst/254443000/254443002.json lines: 24,30
#> file: inst/254443000/254443003.json lines: 30
#> file: inst/254443000/254443004.json lines: 64
#> file: inst/378419000/378419003.json lines: 966,1227
#> file: inst/4098597000/4098597001.json lines: 24,30
#> file: inst/4098597000/4098597002.json lines: 24,30
#> file: inst/4101602000/4101602001.json lines: 24,30
#> file: inst/4101602000/4101602002.json lines: 24,30
#> file: inst/4101602000/4101602003.json lines: 23,29
#> file: inst/4101602000/4101602004.json lines: 73
#> file: inst/4137275000/4137275003.json lines: 23
#> file: inst/4164770000/4164770001.json lines: 24,30
#> file: inst/4164770000/4164770002.json lines: 24,30
#> file: inst/4164770000/4164770003.json lines: 63
#> file: inst/4266367000/4266367003.json lines: 173,929
#> file: inst/436642000/436642004.json lines: 81
#> file: inst/437663000/437663003.json lines: 129,885
```

**Comment by gowthamrao** [comment]
> I propose converting any non-utf8 encoded characters to their utf8 counterparts (e.g. "Sjögren's syndrome")
@ablack3 agreed. 

Similar issue https://github.com/OHDSI/ROhdsiWebApi/issues/139 


> Adding a test that would check to make sure all text files contain only valid utf8 characters

good idea. I think we might benefit from a function that scans contributed json, sql and file names. Optionally makes conversion.
we can add a maintenance script here https://github.com/OHDSI/PhenotypeLibrary/tree/master/extras

> Adding a dataframe/tibble to the package that would contain one row per cohort with metadata, json (as a list column), and sql (as a list column) so that loading the package in R would provide instant access to all phenotype and cohort data the package provides.

This repository, although has a R package in it - is not designed to be used exclusively in an R package. We want to expose each item separately. i.e. we want to be able to do pull request to change one file (e.g. change on json expression of one cohort within a phenotype). ie. the content here should be modified https://github.com/OHDSI/PhenotypeLibrary/tree/master/inst

if we want another file that is essentially appending these individual content into one dataframe object - thats fine by me (as part of package maintenance)

**Comment by ablack3** [comment]
Sounds good. I have a [PR](https://github.com/OHDSI/PhenotypeLibrary/pull/13) with 
- [A automated test to check for non-utf8 characters in json and sql files](https://github.com/OHDSI/PhenotypeLibrary/pull/13/commits/a5559f7522754e5293eee9d1b0fd2b845a86f805)
- [A script that converts all json files to utf8](https://github.com/OHDSI/PhenotypeLibrary/pull/13/commits/393dc8f9388d07b5cd05a8c68c7f79e6b80b5f33)
- [Code to build a dataframe from the souce files in the inst directory as part of package maintenace](https://github.com/OHDSI/PhenotypeLibrary/pull/13/commits/2bbf8257bfca8fe70b04dbdfc00ed8e15e720661)

> This repository, although has a R package in it - is not designed to be used exclusively in an R package. We want to expose each item separately. i.e. we want to be able to do pull request to change one file (e.g. change on json expression of one cohort within a phenotype). ie. the content here should be modified https://github.com/OHDSI/PhenotypeLibrary/tree/master/inst
> 
> if we want another file that is essentially appending these individual content into one dataframe object - thats fine by me (as part of package maintenance)

Yes that's my thought too. The package dataframe is derived from the files in the inst folder. It can be quickly recreated each time those files are updated. The dataframe provides easy access to the phenotype library from R as an alternative to users needing to read in files from the inst directory. The phenotype library dataframe is a downstream/derived object.

**Comment by gowthamrao** [comment]
Names now conform to atlas cohort name constraints
