### ISSUE TITLE
Publish subscribe mechanism for  (e.g. WebSub)

### ISSUE THREAD

**Issue by azimov** [OHDSI/PhenotypeLibrary#14]
Going forward, I see a potential issue occuring when phenotypes update and different end users working with old phenotypes that may have been updated. Implementing a form of publish subscriber model for this would be ideal. For example, following the [WebSub protocol](https://w3c.github.io/websub/) would be one approach. 

In the websub model, 'webhooks' are callbacks that run when updates are published to 'topics' that users intentionally follow. In the case of OHDSI network collaborators this would be implementing tools that automatically run updates to generated cohorts across sites incrementally. This could also provide a model for keeping track of changes in librarians specific phenotype's of interest providing them with updates when related cohorts are changed. They could then plan actions to update cohort diagnostics or results across different network sites.

I don't have a concrete idea of how to implement this exactly, but I do have the use case of wanting to regenerate cohorts when the PhenotypeLibrary definition is updated. Designing a clear, consistent, way to do this would be beneficial.

**Comment by gowthamrao** [comment]
This is a good idea, although i dont know how this maybe implemented. As of right now, i was planning to use a version controlled release cycle. 

But would be very interested in this subscription based model to communicate changes to subscribers.

**Comment by gowthamrao** [comment]
Hey @azimov  can we revisit this? How about using github tags and release

**Comment by gowthamrao** [comment]
Closing issue after talking with @azimov
