### ISSUE TITLE
Possible issue with existing cohort definition 441202003: Anaphylactic reaction by Walsh (Mini-sentinial validated definition)

### ISSUE THREAD

**Issue by ablack3** [OHDSI/PhenotypeLibrary#18]
**Identify the cohort definition**
Cohort 441202003: Anaphylactic reaction by Walsh (Mini-sentinial validated definition)

**Describe the issue**
This cohort definition seems to capture many more events than I would expect. I apologize for the lack of detail but have very limited clinical background to understand what the problem is. I do think that this cohort definition should be reviewed by experts though.

**Screenshots**
I cannot share any screenshots unfortunately but can tell you that I believe the problem has to do with the third part of the cohort definition.

Initial Event Cohort
People having any of the following:
A visit occurrence of Outpatient visit
Having all of the following criteria:   
Having any of the following criteria:
at least 1 occurrences of a drug era of Diphenhydramine hydrochloride5
where event starts between 0 days Before and 0 days After index start date
or at least 1 occurrences of a condition occurrence of Bronchospasm3
where event starts between all days Before and all days After index start date
or at least 1 occurrences of a condition occurrence of Stridor11
where event starts between all days Before and all days After index start date
And having all of the following criteria:
at least 1 occurrences of a drug era of Epinephrine6
where event starts between 0 days Before and 0 days After index start date
and at least 1 occurrences of a condition occurrence of Hypotension7
where event starts between 0 days Before and 0 days After index start date
and at least 1 occurrences of a procedure of Cardiopulmonary resuscition4
where event starts between 0 days Before and 0 days After index start date
And having all of the following criteria:
at least 1 occurrences of a condition occurrence of Allergy unspecified1
where event starts between 0 days Before and 0 days After index start date

**Additional context**
Just want to flag this cohort for a second look by the experts.

**Comment by gowthamrao** [comment]
not in atlas-phenotype.ohdsi.org
