### ISSUE TITLE
Description flipped for Incident and Prevalent cohorts?

### ISSUE THREAD

**Issue by jduke99** [OHDSI/PhenotypeLibrary#24]
**Identify the cohort definition**
Looking at Malignant Melanoma of Skin.  C1 Incident Cohort, but I believe this applies to most if not all Incident vs Prevalent cohorts.

**Describe the issue**
The Description does not show the 365 day prior observation period requirement.  But the JSON code does.  (The JSON appears correct to me (in terms of my understanding of incident and the fact that the count is lower on C1 than C2.)

**Screenshots**
![image](https://user-images.githubusercontent.com/5069947/118827655-93d2de80-b88a-11eb-8266-8829ed7572e2.png)

![image](https://user-images.githubusercontent.com/5069947/118828084-f3c98500-b88a-11eb-9df1-a1a29df46b21.png)

**Additional context**
The incident and prevalent descriptions need to be corrected (ie switched), potentially for every C1 and C2 in the library.

**Comment by jduke99** [comment]
I realize now that this is identical to issue #17.  That issue was posted 6 months ago.

**Comment by gowthamrao** [comment]
Closing issue as we are using a different framework to manage cohort definitions
