### ISSUE TITLE
Add URLs in About

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/PhenotypeLibrary#58]
I had to hunt around to find these URLs and I think adding them to the GitHub ABOUT would be helpful.

- https://data.ohdsi.org/PhenotypeLibrary/
- https://atlas-phenotype.ohdsi.org/

The second link I do not have access to.  Maybe if it is only admins, but if not, instructions on how to get access would be helpful too.

**Comment by gowthamrao** [comment]
@ericaVoss they are documented here https://forums.ohdsi.org/t/ohdsi-phenotype-library-announcements/16910

**Comment by gowthamrao** [comment]
I added reference to the ohdsi forum post on the about page - thank you for that feedback

**Comment by gowthamrao** [comment]
Updated here https://github.com/OHDSI/PhenotypeLibrary/pull/60
