### ISSUE TITLE
T2DM --> Hemoglobin A1c (HbA1c) measurements 

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/PhenotypeLibrary#59]
An issue for Cohort ID 228 - [P] Type 2 Diabetes Mellitus indexed on diagnosis, treatment or lab results

The concept set "Hemoglobin A1c (HbA1c) measurements" should also include the following CONCEPT_ID:
```37393623 - HbA1c level (Diabetes Control and Complications Trial aligned)```

The most common unit is percent (at least in my local DB that uses it)

**Comment by gowthamrao** [comment]
@ericaVoss I think for cohort id is 288, this concept set includes the concept id that you have found to be missing

![image](https://github.com/OHDSI/PhenotypeLibrary/assets/13936600/037a47a4-feb7-4393-945c-84c9cbee957e)
