### ISSUE TITLE
v3.1.6 non-standard concepts to define concept sets

### ISSUE THREAD

**Issue by abbynewbury** [OHDSI/PhenotypeLibrary#69]
Hi, I am not sure if this was changed in newer versions but wanted to mention that for phenotypes 551 and 676, they are defined by non-standard concepts, and thus in the corresponding sql, 
`JOIN #Codesets cs on (co.condition_concept_id = cs.concept_id and cs.codeset_id = 0)`
this most likely won't grab any patients since the non-standard concept ids will be in their co.condition_source_concept_id if I understand correctly. Thanks!

**Comment by gowthamrao** [comment]
You are correct!! I will fix it in future release

> 551
![image](https://github.com/OHDSI/PhenotypeLibrary/assets/13936600/a96a7090-e9a5-420c-869a-8a31827fa5f2)


> 676
![image](https://github.com/OHDSI/PhenotypeLibrary/assets/13936600/d9fb10b9-8e8b-41b1-bccf-b4afea94d1f5)



I think these were standards at one point in time (probably around 2020). 

Interesting use cases for cohort definition logic . Tagging @aostropolets to validate if this is TRUE
