### ISSUE TITLE
Error in IL-23 inhibitor cohorts I submitted

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/PhenotypeLibrary#75]
@gowthamrao , I made an error in the 'New users of IL-23 inhibitors' cohorts (ID 1042 and 1057 in the Phenotype Library).  The conceptset is supposed to contain drugs that are IL-23 inhibitors.  I incorrectly included ustekinumab (which is an IL12/23 inhibitor) and incorrectly omitted guselkumab (which is an IL23 inhibitor, alongside risankizumab and tildrakizumab).  How can we correct these errors?

**Comment by gowthamrao** [comment]
If you send me the correct json, i will replace it and it will be part of next release

**Comment by gowthamrao** [comment]
I made the changes. Should be part of the next version
