### ISSUE TITLE
Unable to use Implementation files - T2DM

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PhenotypeLibrary#8]
Hello,

I was trying to use the T2DM_broad.json file in my Atlas instance to generate the cohort. But when I copy the contents of the file from github and put it in my Atlas Instance, the file doesn't load and I don't see any concept sets or cohort definition being generated. For ex, when I copy the json file the screen looks like below and even after I click on "Reload", I don't see any updates in concept tab of Atlas. Can help with this please. May I kindly check with you on what's the right way to do this?

![image](https://user-images.githubusercontent.com/30723825/77839962-82290600-71b4-11ea-93a9-036d0593177f.png)

**Comment by Alexdavv** [comment]
Hi @SSMK-wq 
Probably you have a new paragraph symbol inside of some of the expressions. Or space symbols might be required somewhere.
Please share the content so people can try this.

Look:
![image](https://user-images.githubusercontent.com/32357692/77846912-00d87000-71c2-11ea-8e97-a62cc8109aa6.png)

**Comment by SSMK-wq** [comment]
Hi @Alexdavv ,

Can you try the content (JSON FILE) which is present under this folder? I just copied the content

PhenotypeLibrary/OHDSI Gold Standard Phenotype Library/Books/Diabetes/Type 2 Broad/Implementation/

**Comment by Alexdavv** [comment]
@SSMK-wq 
It works. Just delete the 1st comment line.
![image](https://user-images.githubusercontent.com/32357692/77847119-4d707b00-71c3-11ea-9427-ae04c728f334.png)
